# Generated by Django 4.1.3 on 2022-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('IsProcess', 'IsProcess'), ('Completed', 'Completed')], default=('IsProcess', 'IsProcess'), max_length=10, null=True),
        ),
    ]
