# Generated by Django 4.1.3 on 2022-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offera',
            new_name='elevator',
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='need_a_car',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_hour',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_loader',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
