# Generated by Django 4.1.3 on 2022-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('subTitle', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
