# Generated by Django 4.1.3 on 2022-11-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_alter_order_offera_service_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='no_action_price',
            new_name='price',
        ),
    ]
